# Generated by Django 4.1.7 on 2023-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_index',
            fields=[
                ('uniq_id', models.TextField()),
                ('product_name', models.TextField(primary_key=True, serialize=False)),
                ('manufacturer', models.TextField()),
                ('price', models.FloatField()),
                ('average_review_rating', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
