# Generated by Django 4.1.7 on 2023-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shopping_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_index',
            name='img',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
