# Generated by Django 4.1.7 on 2023-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shopping_index_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('product_name', models.TextField()),
                ('sale_place', models.TextField()),
                ('add_to_chart', models.BooleanField(default=False)),
            ],
        ),
    ]
