# Generated by Django 4.1.7 on 2023-04-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='add_to_chart',
            new_name='add_to_cart',
        ),
    ]
