# Generated by Django 4.1.7 on 2023-04-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_rename_add_to_chart_cart_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
    ]
